arkmanager/ark-server-tools

- tools/arkmanager
> Changed the script cosmetics and dynamics

- README.md
using $2 for broadcasttext in script -> 
./arkmanager broadcast hello world
will result in a broadcast with text "hello"
./arkmanager broadcast "hello world"
will take all to broadcast
> should user quotation marks for ./arkmanager broadcast

- tools/arkmanager.cfg
As confirmed by Drake, this will be the AppID for the linux files.
Source: http://steamcommunity.com/app/346110/discussions/0/594820656447032287/#c594820656465662918 (Thanks to MrCoder on Steam)
> Sets the correct AppID for linux files

- tools/arkmanager
- tools/arkmanager.cfg
* removed sessionname from startup parameter (its better to define the name in the GameUserSettings.ini)
* renamed update variable to patch
* changed update comparsion
> fixed some stuff

- README.md
- tools/arkmanager
- tools/arkmanager.cfg
Simple fixes :)
Resolves Issue https://github.com/FezVrasta/ark-server-tools/issues/18 and https://github.com/FezVrasta/ark-server-tools/issues/14
> Fixes server stopping, removes error in version checking and corrects typo in readme

- tools/arkmanager.cfg
> Corrects path to appinfo

- README.md
- netinstall.sh
- tools/arkmanager
- tools/arkmanager.cfg
Cherry-pick commits from master, and merge master into 1.2-dev, as requested in #70
Some corrections have been made to commits involving netinstaller.
> Merge master into 1.2-dev

- tools/arkmanager
Fixes the display issue in #66
> Use getCurrentVersion after update

- tools/install.sh
As requested in https://github.com/FezVrasta/ark-server-tools/issues/67
> Includes a copy of the newest config file on installation

- README.md
- tools/arkmanager
I wrote a function that waits for world save to be done before performing update. I know it's just temporary solution until RCON and save-on-exit is implemented but might be useful until then.
My bash coding is not great so there might be better way to implement that if you come up with something.
> Waiting for world save before update.

- README.md
- tools/arkmanager
Reverts FezVrasta/ark-server-tools#74
> Revert "Waiting for world save before update."

- tools/arkmanager
> Fixed missing terminating quotation mark.

- tools/install.sh
> Modify DAEMON variable in systemd init script

- tools/arkmanager
- tools/arkmanager.cfg
Add ark backup feature as suggested in #98
> Add ark backup feature

- README.md
- tools/arkmanager
Merge the two hotfixes from master into 1.3-dev
> Merge Hotfixes from master into 1.3-dev

- tools/arkmanager
This improves the backup feature to close some race windows where the backup could be inconsistent.
> Make backup function more robust

- tools/arkmanager
Fixes: 201c887 (added upgrade command, added support for release channels)
> Fix typo in doUpgrade

- tools/arkmanager
- tools/arkmanager.cfg
This missed the 1.3 release.  See #21
> Add option to warn players before update

- tools/arkmanager
* Ignore the steamcmd_user when validating the environment
* Add a -- separator when installing, so that --me is interpreted as
an argument to the script rather than an argument to bash
This should resolve #163
> Fix issues with user-install

- tools/arkmanager
- tools/arkmanager.cfg
This will restart the server if it crashes after going online.  This should satisfy #64
> Add server auto-restart

- tools/install.sh
Install script was putting "me" instead of "--me" into config file
> Fix issue with user-install in install.sh

- tools/arkmanager
> Fix "infinite" update warn

- tools/arkmanager
This set of commits should allow upgrading and uninstalling when running arkmanager as root.
> Allow upgrade / uninstall when running as root

- tools/arkmanager
Autorestart wasn't working.  This should fix that.
> Fix autorestart

- tools/arkmanager
> Add missing .modbranch file creation

- tools/install.sh
> Fix typo in Debian and Redhat systemd installs

- tools/arkmanager
This was suggested by @TuRz4m in #279.
> Add support for updating when nobody is connected

- tools/arkmanager
This was requested (in a round-about way) in #307.
> Add --version option

- tools/arkmanager
This was supposed to be part of #301, but was missed.
> Take RCONPort from GameUserSettings.ini with default

- netinstall.sh
This allows one to see the output of the install command
> Add --verbose and --output=/path/to/file options

- tools/arkmanager
- tools/arkmanager.cfg
> Add option to warn on shutdown and restart

- tools/arkmanager
> Remove unnecessary shifts from command processing

- tools/arkmanager
> Fix typo in stop/restart warn

- tools/arkmanager
> Add missing semicolon

- tools/arkmanager
> Fix typo in RCON handling

- tools/arkmanager
This should make issues like #360 less mysterious.
> Warn when the SavedArks directory is not writable

- tools/arkmanager
> Change message after server is started

- tools/arkmanager.cfg
> Remove unused 'servicename' variable

- tools/arkmanager
> Warn when a mod is requested but not installed

- tools/arkmanager
Fixes: d37176a Warn when a mod is requested but not installed
This should fix #373
> Fix typo in non-installed mod check

- tools/arkmanager
Fixes: 74fe4c9 Remove files removed by Steam update
This should fix #375
> Fix typo in staging directory based file removal

- tools/arkmanager
This should resolve issues caused by leftover files in installed mods.
> Remove files that have been removed in mods

- tools/arkmanager
Fixes: 9c35974 Improve mod update behaviour
> Fix the path to appworkshop_appid.acf

- tools/arkmanager
This adds commands to uninstall and reinstall mods to the Mods directory.  This should satisfy #242.
> Add uninstallmod and reinstallmod

- README.asciidoc
- netinstall.sh
- tools/arkmanager
__Allow `{time}` in warning reason__
This allows for messages where the time remaining is part of the reason text.
__Fix a typo in the documentation__
The documentation had `{modnamesupdate}` where it should have had `{modnamesupdated}`
__`" \n "` added to empty response message__
Server response when a command returns no response is
`"Server received, But no response!! \n "` where `\n` is a newline.
__Fix an error in doWarn that was causing duplicate warnings__
This should fix #488 
__Actually cancel warning when Ctrl-C etc are pressed__
This should cancel the update / shutdown / restart when the administrator attempts to cancel the update
__Fix warning in `runSteamCMDspinner`__
Fixes a spurious `bad file descriptor` warning
__Fix `restart --warn` broadcasting shutdown message__
This …
> Various fixes for new features

- README.asciidoc
- tools/arkmanager
- tools/install.sh
* Merge master
* Support printing the updated version number in the update restart warning message
> 1.6 dev fixes

- README.asciidoc
- tools/arkmanager
* Fix `A2S_PLAYERS` query usage - count players that are named
* Add `installmods` command to install all mods that are specified in the config
> 1.6 dev.unstable

- tools/arkmanager
Add support for restarting using the service after updating
> Add support for restarting using service

- tools/arkmanager
id -u returns the effective user id
> Reliable user id detection

- tools/arkmanager
Managing multiple servers and having to rollback every now and then I made this little patch to save me some time of browsing through backup-files and thought it might be helpful for someone else too :)
> Add instance name to backup filename

- tools/arkmanager
This fixes an issue I had when running the server manager via cron jobs. See #1051
> add full Path to runuser

- tools/arkmanager.cfg
I believe that adding a comment here could help with understanding how instances work 😄
> Add comment for instances

- tools/arkmanager
> Fix typo of arkBackupPostCommand

- README.asciidoc
- tools/arkmanager
as required in issue 1056 among others, I have implemented a function to restore a backup.
> add Restore option

- tools/arkmanager
Fixed from the my pull request - https://github.com/arkmanager/ark-server-tools/pull/1188
Sorry...)
> fixed arkAutoUpdateOnStart => arkbackupcompress
