arkmanager/ark-server-tools

tools/arkmanager.cfg
We need to include the full path to the script in order to run it.
=> Fixes startup of the server with full path

tools/arkmanager, tools/arkmanager.cfg, tools/install.sh
EXECPREFIX and INSTALL_ROOT can be used by distributions for packaging and to put the script where they want to put it (e.g. /usr, /usr/games, /usr/local, /opt/arkmanager)
Paths should also be quoted as they may contain spaces.
This also imports the user config into arkmanager - e.g. if a beefy host houses multiple game servers.  If run from the init script, it should source the config from the same file as the init script sources it from.
The custom server variables allow the definition of custom server variables - though most of the variables should be specified in the ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini file anyway.
I have re-added the Port option.  The port opened by the server is one higher than that specified in the options, so this corrects for that.
=> Dev#1.1 - config and distro compatibility

tools/arkmanager, tools/install.sh
The first patch of this series parses the output of app_info_print (which is line-based, similar in structure to json, and easily parsed by bash) and extracts the buildid of the public branch.
I found a typo I made in the path modification for the init scripts, so I have fixed that.
The install script now also modifies the new config file to match the requested install user.
=> Dev#1.1 - fixes

tools/install.sh, tools/lsb/arkdaemon, tools/redhat/arkdaemon, tools/systemd/arkdaemon.init, tools/systemd/arkdeamon.service
This adds the systemd unit file to redhat, and copies either a distribution-specific or distribution-agnostic init script to /usr/libexec/arkmanager
It renames arkdaemon.service to arkmanager.service to be in line with the other init scripts
It also uses the INSTALL_ROOT and EXECPREFIX variables to allow packaging and installing to custom prefixes.
=> Dev#1.1 - systemd

tools/arkmanager
Closes a window where an update could be missed (by grabbing the installed version directly from the app manifest), and should refresh the available version from Steam (using the app_info_update command).
=> Dev#1.1 app_info_update (issue #53)

tools/arkmanager.cfg
Email was removed from arkmanager some commits ago. Having it in the config files could possibly cause issues with dropped items vanishing.
Reported in https://github.com/FezVrasta/ark-server-tools/issues/81
=> Removes email from config

tools/arkmanager
This changes the current working directory to the ARK server root directory when starting, in order to prevent potentially undefined behaviour.
=> Change to the ark server root directory

tools/arkmanager, tools/install.sh
9313d72 should make it more obvious what effects the environment variables affecting install have.
f7ccbfe takes into account that some distributions (RedHat-based in particular) have lsof in /usr/sbin, while many other distributions have lsof in /usr/bin.  This fixes #93 where lsof is in /usr/sbin/lsof
=> Explain variables affecting install; Discover path of lsof

tools/arkmanager
Moves the check for being able to write to the parent of arkserverroot to the install function.
Allows pre-creation of the arkserverroot.
For my install I created /ssh/ark as root, and changed its ownership to steam before running the install script. Steam does not have write permission to /ssd, but it does have write permission to /ssh/ark
Before this fix, I would get an error on every script run.
Ref Issue #110
=> Moved arkserverroot parent directory check to the install function

tools/arkmanager
d34f2ac implements a simple RCON client in perl as an inline script, and adds two new commands (`saveworld` and `broadcast`) to arkmanager.  This should resolve #54.
120df3d queries the server to get the server name (including version) and number of players online.  This was suggested in #57.
The server responds to broadcasts (and probably some other commands) with "Server received, But no response!!".  accc3d4 hides this unhelpful response.
61068b2 adds a `rconcmd` command to arkmanager.
=> RCON and Server Query implementation

tools/arkmanager
When making a backup of the server files, we should preserve the source file attributes, especially the file timestamps.
Preserving the file timestamps will allow the server admin to see exactly when the world was last saved, rather than what time the backup command was run.
=> Preserve timestamps when copying the server files during backup

tools/arkmanager
There should be space between arkmanager and [OPTION].
=> Fix: typo in usage

tools/arkmanager
2110bc7 shuts down the server using SIGINT, which invokes the CtrlCHandler and saves the world.
3759904 moves the PID discovery out of doStop, and uses it to check if the server is running.  This should prevent other instances of the server from being detected and causing startup to fail.
ac41f14 waits for up to 10 seconds for the server to stop, and if the server is still running after 10 seconds then it kills it.  A normal shutdown generally only takes 2-3 seconds.
f2ff580 reduces the wait between stop and start to 1 second.  This and the previous commit should reduce if not eliminate the likely cause of #129.
=> 1.3 dev stop/restart

tools/arkmanager, tools/arkmanager.cfg, tools/install.sh
f58645c adds the ability to install using a special "me" user, which will cause the installer to perform a user-local install instead of a system-wide install, as suggested in #123.
b52770f adds support for multiple commands in a single invocation, as suggested in #68.
2e65228 informs the user which command was not understood.
562bb93 allows the user to specify a configuration name or config file from which to source overrides for variables in the system and/or user config files. Should allow what was suggested in #62.
=> 1.3 dev features

tools/arkmanager, tools/arkmanager.cfg
2e8e3b6 fixes where I missed extracting the world name from the server map path.
0aa7546 adds support for the `-MapModId` map specification introduced in ARK: Survival Evolved 193.0
=> 1.3-dev mod support

netinstall.sh, tools/arkmanager, tools/arkmanager.cfg
3e0fa90 moves the script version into the script.
10a49b7 retrieves the latest commit on the selected branch, and injects it into the script during install.
74b665c adds hotfix support by retrieving the latest commit and comparing it against the commit injected above
34a3ec8 retries with the master channel if the selected channel branch is not found, and aborts if the master channel is not found.
6ce1847 injects the version from the .version file into the script during install.
8a7f6d2 fixes the issue reported in #153 and #154 where /bin/sh is not bash, by running the install script using bash.
=> Move script version to script; add hotfix support

tools/arkmanager, tools/arkmanager.cfg
2ef86c9 adds mod installation support.
5c5cd58 retries the mod download when steamcmd times out - for example, it takes a few tries to download a large mod such as Survival of the Fittest.
5b9a3db adds the mod installation support to the commands supported by arkmanager.
This should satisfy #157
=> Mod Installation support

README.md, tools/arkmanager, tools/arkmanager.cfg
First, merge from master, resolving the conflict due to doInstallMod and doWarnUpdate being in the same place in the script
c0793a8 makes the update warning message customisable[en_UK]/customizable[en_US].
b0e41d0 adds `update --warn` to the list of commands in the readme.
=> Add option to warn players before update

tools/arkmanager, tools/arkmanager.cfg, tools/lsb/arkdaemon, tools/openrc/arkdaemon, tools/redhat/arkdaemon, tools/systemd/arkdeamon.service
0080e3c adds support for starting / stopping multiple servers running on the same machine, by adding an `--all` option to start, stop and restart.
d6fc1f7 updates the init scripts to use the feature added in the above commit.
b294cb6 adds support for ARK flags (such as `-OnlyAdminRejoinAsSpectator`).
3eb123f adds example config options (commented out) to the config file.
544a782 adds support for the AltSaveDirectoryName ARK option when performing a backup.
=> 1.4 Features

tools/arkmanager
This merges the different update commands, and adds `--verify` and `--update-mods` options.
c329f28 begins moving the argument processing into the `doUpdate` function.
e3dbe28 merges the safe update into the `doUpdate` function
e86f7b0 merges the warn update into the `doUpdate` function, with the actual warning logic in `doUpdateWarn`.
At this point, all of the options can be handled by `doUpdate`.
9b5435f passes update option handling to `doUpdate`, with the main argument processor grabbing all of the double-dash options after the update command.
39c649d merges the `forceUpdate` function into `doUpdate` so we can add better handling
fddbec4 adds a `--validate` option to the update command, which allows one to force a re-validation of the ARK server files.
2207ff1 moves the mod …
=> 1.4 dev#modupdate

netinstall.sh, tools/arkmanager, tools/arkmanager.cfg, tools/install.sh, tools/uninstall-user.sh, tools/uninstall.sh
First merge in the hotfixes from the master branch.
The first few commits set the installer script up to handle upgrades better, and make options more discoverable.
37014ec adds better argument handling to the install script.
563c34b adds command-line arguments to the install script for the `PREFIX`, `EXECPREFIX` and `INSTALL_ROOT` distro-helper variables.
f597644 improves the installer script usage message.
b86967c adds a `BINDIR` variable and associated command-line argument to the installer script
3977190 adds the `PREFIX` variable to the global install
bfca58c adds a `LIBEXECDIR` variable and associated command-line argument to the installer script
d40d9d9 always writes the `arkmanager.cfg.NEW` file, and moves it to `arkmanager.cfg` if that file doesn't exist.
283c04d adds settings …
=> Improve install and add uninstall script

tools/arkmanager
Not using isTheServerUp, as doSaveWorld should return immediately
if the server is not up.
=> Save world before update

tools/arkmanager
38d9b4e is a hotfix to save the world before stopping the server
f60556c merges this into 1.4-dev, moving it into place.
4e7fc8f adds a `--saveworld` option to the `update` command
c319465 slightly rearranges the help text to make it more obvious that the `update` command can take multiple options.
=> Add `--saveworld` option to update

tools/arkmanager
Merge from the 1.3 hotfix.
The config option e.g. ark_bRawSockets="" should result in the
...?bRawSockets
This should help resolve #178 on 1.4-dev
=> Allow empty options

README.md, tools/arkmanager, tools/arkmanager.cfg
Two simple commits to make life easier with these frequent updates to ARK.
* Controllable by true/false in the configuration files.
* Only performs a backup if there actually is a new version available.
=> Allow backing up prior to updating the server

tools/install.sh
install.sh was altering arkmaanger.cfg instead of arkmanager.cfg.NEW; 94eda24 fixes this.
The config modification was still assuming that $1 was the user.  72e0543 fixes this.
This should resolve the majority of #188
=> Fix install.sh

tools/arkmanager, tools/arkmanager.cfg
The Linux version of some mods don't work at all with the dedicated
server.  Allow the administrator to configure which mod branch
to grab (Windows or Linux).
This should fix #196
=> Add option to select mod OS

tools/arkmanager
Running arkmanager as root in order to upgrade without sudo wasn't working - it would say that the steamcmd user was invalid.  a307643 fixes this.
1505aa8 runs any other commands as the steamcmd_user when arkmanager is run as root.
=> Fix error in running as root

tools/arkmanager
The `!` (not) unary operator under `[ ... ]` apparently has a lower precedence than the `-o` (or) binary operator.  This should fix the resulting error in the mod file update time comparison.
=> Fix error in mod file update time comparison

tools/install.sh
The installer was trying to put the uninstaller into /usr/share/arkmanager, which wasn't working as it was failing to create the directory.  Put it into /usr/libexec/arkmanager instead, as expected by everything else.  This should resolve #194
=> Put uninstaller script into libexec

tools/install.sh
This should fix the `mkdir: cannot create directory ‘’: No such file or directory` encountered when trying to install on Debian 8+ or Ubuntu 15+.
Fixes: bfca58c
=> Fix typo in install script

tools/arkmanager, tools/arkmanager.cfg
e4d4218 changes the default mod branch to be Windows, and records the current mod branch in a `.modbranch` file in the mod directory.  If the requested mod branch doesn't match the current mod branch, then the mod is removed and re-added.  This should fix #196.
167781e adds non-anonymous steamcmd login, using the `steamlogin=user` option in the arkmanager config file.  This should fix #205.
17dd16a adds support for options of the form `-opt=val`, by specifying `arkopt_opt=val` in the arkmanager config file.  This should fix #204.
d27eff2 logs the command that is used to launch the server, which should make it easier for the user to verify what commandline is used and to launch the server separately from ARK Server Tools.
fa7649d allow the user to specify `arkflag_<optname>=""` - e.g. …
=> 1.4 enhancements

tools/arkmanager
This will abort an upgrade if the `arkstChannel` is invalid (e.g. as in #209).  It will also display the available channels.
=> Abort upgrade if arkstChannel is invalid

tools/arkmanager
This should prevent an accidental downgrade due to `arkstChannel` being on an older channel.
=> Fix hotfix detection; don't downgrade

tools/arkmanager
This queries the Steam API to determine if the server has registered with the Steam network.  If it has, then it also prints the arkservers.net link for the admin to check if the server is visible to the outside world.  If the server is not visible to the outside world, even after clicking the "Add this server to the database" button on the arkservers.net page, then the admin needs to check their firewall and router settings to make sure the necessary ports are not blocked.
=> Query Steam API for server status

tools/install.sh
Adds new options to and removes deprecated options from ARK Server Tools configuration file
This was suggested in #215, and should resolve issues where e.g. arkmanager still shows an old version despite a successful upgrade.
=> Upgrade config file with new options on install

tools/arkmanager
Use the `ark_MultiHome` setting for determining what address to query the server on.  If `ark_MultiHome` is not set, fall back to localhost.  This was suggested in #230, and should resolve #234.
=> Add support for MultiHome setting

tools/arkmanager
I discovered an error in the MultiHome support added in #235, where lsof errors out when MultiHome is not used.  This should fix that error.
=> Fix error in MultiHome support

tools/systemd/arkdaemon.init
Set environment variable TERM to "dumb" if it is not set. This suppresses errors from "tput", which are shown in eg. "systemctl status arkmanager.service". The error which tput gives without TERM set is "tput: No value for $TERM and no -T specified".
=> Set TERM to "dumb" if TERM is not set

tools/arkmanager, tools/systemd/arkdaemon.init
Moves the `export TERM="${TERM:-dumb}"` fix in #241 from tools/systemd/arkdaemon.init to tools/arkmanager
This should also clean up the conflict that currently prevents 1.4-dev from being merged into master, so we can stabilize v1.4
=> Pull #241 from master into 1.4-dev

netinstall.sh
`shift 2` will fail to shift off any arguments if there are less than 2 arguments.
Convert `shift 2` to two separate `shift` statements.
This should resolve #248
=> Fix error causing netinstall to fail with one argument

tools/arkmanager
This fixes a typo in the `upgrade-tools` command when running as root.  This should resolve #258.
=> Fix typo in `upgrade-tools` when running as root

tools/arkmanager
A mistake in `isModUpdateNeeded` was causing the test for new or updated files to be run as a subprocess, and the result of that was not being passed up.  This switches it around so the file listing is passed through using process substitution.  This should fix #257
=> Fix mod update not being detected

tools/install.sh
The `chown` for `/var/log/arktools` and `/etc/arkmanager/arkmanager.cfg` was still using `$1` (which would be empty after argument processing) instead of `$steamcmd_user`.
This commit should fix the issue reported by @Lihis in #260.
=> Fix /var/log/arktools and arkmanager.cfg ownership

tools/arkmanager
This will check if anybody's connected once a minute while warning the players.  If nobody's connected, then it will immediately proceed with the update.
=> When warning players, update now if nobody's there

tools/arkmanager
* Due to a bug in the minutes remaining check,
the warning period was defaulting to 90 seconds,
when it should have defaulted to 60 minutes.
* The time between 2 minutes and 90 seconds was
60 seconds, when it should be 30 seconds
=> Fix a couple of bugs in update --warn

tools/arkmanager, tools/arkmanager.cfg
This downloads the update to a staging directory before initiating the shutdown warning and update.  This was requested in #237.
In order to save some space, this creates hard links to the files in the staging directory, relying on the fact that `steamcmd` doesn't modify files in-place, but rather downloads them to `steamapps/downloading/<appid>` then removes the old files and replaces them with the new files, and files outside `ShooterGame/Saved` are not modified by `ShooterGameServer`.
This space saving does require that `$arkserverroot` and `$arkStagingDir` are on the same filesystem.  If those are not on the same filesystem, then it will use `rsync` to copy the files.
=> Add support for downloading updates before applying

tools/arkmanager
This should prevent the snafu that appears to have occurred in #295 (multiple concurrent updates resulting in a corrupt install) from occurring.
=> Prevent multiple updates from occurring concurrently

tools/arkmanager
Returns the status from the last command run.
Also returns a non-zero status from checkupdate when an update is required.
This was requested (in a round-about way) in #306.
=> Return the status from the last command run

tools/arkmanager
The `sed -n` was missed, thus causing arkmanager to be unable
to get the password or RCON port from GameUserSettings.ini
Fixes: 30aea93bd6572df640d04951617bbe477571dea7
This should fix #314
=> Fix retrieving settings from ini file

tools/arkmanager
When `workshop_download_item` is executed, the Steam API will download not just the specified mod, but also every other mod that has ever been installed by that SteamCMD instance.
Wait for those to download and update when downloading the mod.
=> Wait for SteamCMD to download mod

tools/arkmanager
Fixes an annoying syntax highlighting issue where everything from the line patched in this commit to the end is syntax highlighted as if it is in a multi-line string.
=> Fix annoying syntax highlighting issue

tools/arkmanager
448945a was created in response to a comment on c13afcb.
de298e8 fixes a mistake where the useconfig command wasn't updated in 6606ed3.
73a8593 adds the new options to stop and restart to the help output.
=> Add --saveworld to stop and restart; fix useconfig

tools/arkmanager, tools/arkmanager.cfg, tools/install.sh, tools/instance.cfg.example, tools/lsb/arkdaemon, tools/migrate-config.sh, tools/migrate-main-instance.sh, tools/openrc/arkdaemon, tools/redhat/arkdaemon, tools/systemd/arkmanager.init, tools/upstart/arkmanager.conf
This adds support for each command to be run on a set of instances.
This was requested in #290.
This instance support supplements the useconfig command.
If the core config contains instance-specific settings, and the main instance config file doesn't exist, then the instance settings are migrated out of the core config and into the main instance config file, and that instance is set as the default instance so as not to break existing scripts.
The default instance can be set using the `defaultinstance` setting in arkmanager.cfg
Instance config files are stored in /etc/arkmanager/instances and/or ~/.config/arkmanager/instances.
This also brings multi-instance support to all of the init scripts - the LSB, RedHat and OpenRC init scripts use the <service>.<instance> naming, with the option to …
=> Add per-command multi-instance support

tools/arkmanager, tools/arkmanager.cfg
This allows the game server administrator to specify the maximum backup size in MB. The oldest backups will be removed until the backup directory size is below this size.
A similar capability (removing backups beyond a certain age) was requested in #300.
=>  Implement old backup removal by limiting backup size

tools/arkmanager
This should point the user to the cause of the `Negative length` error, and should replace most if not all occurrences of that error with a more appropriate error.
=> Warn when ServerAdminPassword is empty

tools/install.sh, tools/systemd/arkmanager@.service, tools/upstart/arkmanager-instance.conf
Have systemd and upstart directly run the script as the user specified during install.
Previously, they were monitoring and controlling the outer process running as root.  Thus stopping the service may not have worked under systemd or upstart.
=> Have systemd (and upstart) run the script as the user

tools/arkmanager
Remove appworkshop_346110.acf before updating the mod, so that steamcmd doesn't try to update every other mod.
Check the exit status of steamcmd when downloading the mod - it returns a non-zero status when the update fails.
1862ccd adds a spinner when running steamcmd commands, and a `--verbose` option that shows the output of steam operations
=> Improve mod update behaviour

tools/arkmanager
Give up on trying to prevent steamcmd from updating every other workshop item it has downloaded.  Instead, give it a certain number of retries, and check if the app's workshop downloads directory exists.
This should fix #382.
c1a1dc7 also adds the ability to choose whether to show progress using dots or a spinner.
65c9233 defaults to using dots when the output is not a terminal - e.g. when output is going to a log file.
=> Fix mod updating re-downloading mod

tools/arkmanager
Replaces the `Server received, But no response!!` return from an RCON command with `Command processed`.
=> Replace empty server response with "Command processed"

tools/arkmanager
This informs the user what config file is sourced for each instance.  It also limits each instance to one config file.
=> Add configfile name to list-instances

tools/arkmanager
Fixes: e48bd5b830a16fc5f30deb19a880b9443705259b Add configfile name to
list-instances
This should fix #414
=> Fix typo in useConfig

tools/arkmanager
Perl uses `eq` to compare strings, not `==`.
Fixes 653e934268c876ac17bafa31998b9bb67c44abb6 Replace empty server
response with "Command processed"
This should fix #417
=> Fix typo when comparing strings

README.asciidoc
Default non-privileged instance-config path seems to have changed to ~/.config/
=> Default non-privileged instance-config path

README.asciidoc, netinstall.sh, tools/arkmanager, tools/arkmanager.cfg, tools/install.sh, tools/systemd/arkmanager.service
Fixes backported to 1.5:
* Use `serverMapModId` to set map name and `MapModID` option
* Return `-1` from `numplayers` if server unreachable
* Fix a couple of potential issues with player count checking
* Fix an inconsistency between `install.sh` and `arkmanager.init`
* ` \n ` added to empty response message
* Fix update `--force` with `arkStagingDir`
* Fix `--stagingdir=` parameter
* Change systemd service type to forking
* Add `RemainAfterExit=yes` to `arkmanager.service`
* Create the saved arks directory if it doesn't exist
* Default non-privileged instance-config path
* Exclude Primitive+ from mod download and extraction
* Prevent server start during update
* Fix interaction between start and update
* Fix error typo
* Fix double-start when auto-update is enabled
* Restart the server if …
=> Release ARK Server Tools v1.6

tools/arkmanager
fixes the warning message spam: "lsof: no pwd entry for UID 999" in docker container
=> Add -w argument to the lsof command

tools/arkmanager
This will delay up to a set amount of time before starting the rest of the instances if defaultinstance_max is defined in the arkmanager.cfg file. Setting the value to 0 will cause no delay or not setting a value will cause no delay.
=> Delay until instance starts.

tools/arkmanager
I have added a variable within the script that can be set to 1 (via a patch, most likely) if the program is installed through a system package manager. This modifies the doUpgradeTools() and doUninstallTools() functions to advise a user to uninstall or install through the system's package manager.
This is not intended to be user-configurable (hence not including inside the config file), instead it should be set by the downstream maintainers during packaging.
resolves #1125
=> Disable updating and uninstalling if installed through package manager

tools/install.sh
just a tiny typo in the installer usage section
=> small typo

README.asciidoc
Using 27016 is invalid by default. Using 27015 in basic instructions should be better.
=> Update invalid steam query port number on README.md
